name: DeathTracker
version: ${project.version}
main: me.roopekoo.deathtracker.DeathTracker
api-version: 1.16
authors: [ Roopekoo ]
description: Calculates players' deaths and death rate per time unit
commands:
  getdeaths:
    description: 'Get deaths for a player'
    usage: /<command> [player] [time | deaths]
  deathstats:
    description: 'Get statistics of the top 10 most and least mortal player'
    usage: /<command> [deaths | deathrate | immortals] (high | low)

